/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.triageapplication;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int drawer_shadow=0x7f020000;
        public static final int ic_drawer=0x7f020001;
        public static final int ic_launcher=0x7f020002;
    }
    public static final class id {
        public static final int action_settings=0x7f080029;
        public static final int arrival_time_title=0x7f080000;
        public static final int back=0x7f080024;
        public static final int back_from_visit_records=0x7f080028;
        public static final int back_to_vitals_from_new_vitals=0x7f080017;
        public static final int blood_pressure_text=0x7f08000c;
        public static final int cancel_new_visit_record_button=0x7f080001;
        public static final int chosen_arrival_date=0x7f080004;
        public static final int chosen_arrival_time=0x7f080003;
        public static final int create_new_vitals_record=0x7f08000d;
        public static final int create_visit_record=0x7f080026;
        public static final int diastolic_blood_pressure=0x7f080018;
        public static final int diastolic_blood_pressure_text=0x7f08000a;
        public static final int dob=0x7f080022;
        public static final int dob_title=0x7f080021;
        public static final int error_message=0x7f080014;
        public static final int from_edit_visit_record_back=0x7f080010;
        public static final int healthCardField=0x7f080012;
        public static final int health_card_number=0x7f080020;
        public static final int health_card_number_title=0x7f08001f;
        public static final int heart_rate=0x7f08001b;
        public static final int heart_rate_text=0x7f08000b;
        public static final int instructions=0x7f080011;
        public static final int invalid_entry=0x7f08001c;
        public static final int new_vitals_instructions=0x7f080015;
        public static final int patient_arrival_date_title=0x7f080005;
        public static final int patient_information=0x7f08001e;
        public static final int patient_name_title=0x7f08001d;
        public static final int save_changes=0x7f080025;
        public static final int set_arrival_date_button=0x7f080006;
        public static final int set_arrival_time_button=0x7f080007;
        public static final int submitButton=0x7f080013;
        public static final int submit_arrival_info=0x7f080002;
        public static final int submit_new_vitals=0x7f080016;
        public static final int systolic_blood_pressure=0x7f080019;
        public static final int systolic_blood_pressure_text=0x7f080009;
        public static final int temperature=0x7f08001a;
        public static final int temperature_text=0x7f080008;
        public static final int view_visit_record=0x7f08000e;
        public static final int view_visit_records=0x7f080023;
        public static final int visit_records=0x7f080027;
        public static final int vital_sign=0x7f08000f;
    }
    public static final class layout {
        public static final int activity_create_visit_record=0x7f030000;
        public static final int activity_edit_visit_record=0x7f030001;
        public static final int activity_main=0x7f030002;
        public static final int activity_new_vitals=0x7f030003;
        public static final int activity_patient=0x7f030004;
        public static final int activity_visit_records=0x7f030005;
    }
    public static final class menu {
        public static final int create_visit_record=0x7f070000;
        public static final int edit_visit_record=0x7f070001;
        public static final int global=0x7f070002;
        public static final int main=0x7f070003;
        public static final int new_vitals=0x7f070004;
        public static final int patient=0x7f070005;
        public static final int visit_records=0x7f070006;
    }
    public static final class string {
        public static final int action_settings=0x7f050002;
        public static final int app_name=0x7f050000;
        public static final int arrival_date_title=0x7f050011;
        public static final int arrival_time_title=0x7f050010;
        public static final int back=0x7f05000b;
        public static final int cancel_new_visit_record_button=0x7f050012;
        public static final int create_new_vitals_record_button=0x7f050014;
        public static final int create_visit_record_button_title=0x7f05000e;
        public static final int diastolic_blood_pressure=0x7f05001b;
        public static final int dob_title=0x7f05000a;
        public static final int edit_recent_vitals_button=0x7f050015;
        public static final int health_card_number_title=0x7f050009;
        public static final int heart_rate=0x7f05001e;
        public static final int hello_world=0x7f050001;
        public static final int new_vitals_instructions=0x7f05001a;
        public static final int patient_information=0x7f050007;
        public static final int patient_name_title=0x7f050008;
        public static final int save_changes=0x7f05001f;
        public static final int search_instruction=0x7f050005;
        public static final int set_arrival_date_button=0x7f050017;
        public static final int set_arrival_time_button=0x7f050016;
        public static final int submit=0x7f050004;
        public static final int systolic_blood_pressure=0x7f05001c;
        public static final int temperature=0x7f05001d;
        public static final int title_activity_create_visit_record=0x7f05000f;
        public static final int title_activity_edit_visit_record=0x7f050013;
        public static final int title_activity_main=0x7f050003;
        public static final int title_activity_new_vitals=0x7f050019;
        public static final int title_activity_patient=0x7f050006;
        public static final int title_activity_visit_records=0x7f05000d;
        public static final int view_visit_records=0x7f050018;
        public static final int view_visit_records_title_button=0x7f05000c;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
